### ISSUE TITLE
unable to install with npm

### ISSUE THREAD

**Issue by greaneym** [digitalbazaar/jsonld-cli#3]
I can't install the jsonld-cli because npm fails on installing contextify.
contextify@0.1.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the contextify@0.1.15 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.

How do I fix this please? I am not an expert node.js user.
thanks,

**Comment by mattcollier** [comment]
@greaneym Take a look at these installation prerequisites: https://github.com/brianmcd/contextify#installation-issues

**Comment by greaneym** [comment]
Hi, thanks for the page info.
I updated the node-gyp version install but that is still calling contexify.

The version of node I am using does not need contexify. I tried installing
jsonld-cli by asking node to --skip=contextify but that did not work.
Any suggestions on how to install without contexify?  Thanks.

**Comment by mattcollier** [comment]
At this time, this module still depends on contextify, so you will want to make sure it can build properly with node-gyp which means that you'll need to make sure that you you have setup all the node-gyp dependencies for your OS enumerated here: https://github.com/nodejs/node-gyp#installation

**Comment by greaneym** [comment]
thanks will take a look.

**Comment by jaw111** [comment]
Seems this is still an issue... is there a pre-built version available for download?

**Comment by jaw111** [comment]
```
2727 silly lifecycle contextify@0.1.15~install: Args: [ '/d /s /c', 'node-gyp rebuild' ]
2728 silly lifecycle contextify@0.1.15~install: Returned: code: 1  signal: null
2729 info lifecycle contextify@0.1.15~install: Failed to exec install script
2730 verbose unlock done using C:\Users\nlv01111\AppData\Roaming\npm-cache\_locks\staging-d866d42d2696256f.lock for C:\Users\nlv01111\AppData\Roaming\npm\node_modules\.staging
2731 verbose stack Error: contextify@0.1.15 install: `node-gyp rebuild`
2731 verbose stack Exit status 1
2731 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
2731 verbose stack     at emitTwo (events.js:126:13)
2731 verbose stack     at EventEmitter.emit (events.js:214:7)
2731 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
2731 verbose stack     at emitTwo (events.js:126:13)
2731 verbose stack     at ChildProcess.emit (events.js:214:7)
2731 verbose stack     at maybeClose (internal/child_process.js:925:16)
2731 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
2732 verbose pkgid contextify@0.1.15
2733 verbose cwd C:\Windows\system32
2734 verbose Windows_NT 6.1.7601
2735 verbose argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "jsonld-cli"
2736 verbose node v8.9.1
2737 verbose npm  v5.5.1
2738 error code ELIFECYCLE
2739 error errno 1
2740 error contextify@0.1.15 install: `node-gyp rebuild`
2740 error Exit status 1
2741 error Failed at the contextify@0.1.15 install script.
2741 error This is probably not a problem with npm. There is likely additional logging output above.
2742 verbose exit [ 1, true ]
```

**Comment by davidlehn** [comment]
I'm not sure what the problem was above, but contextify was causing issues for everyone.  I updated `jsonld-cli` and `jsonld-request` dependencies and things install again on linux with a recent node.

**Comment by jaw111** [comment]
@davidlehn yes, that has solved the problem, thanks for the prompt response :+1:
