### ISSUE TITLE
File input mistakenly interpreted as remote resource

### ISSUE THREAD

**Issue by jindrichmynarz** [digitalbazaar/jsonld-cli#5]
When I want to apply the tool to a local file, which should be supported according to the documentation, I get an error caused by the tool trying to load the local file as URL.

Here, both `frame.jsonld` and `data.jsonld` are paths to local files: 

```
jsonld frame -f frame.jsonld data.jsonld
```

Produces:

```
jsonld.FrameError: Could not expand input before framing.
    at /usr/local/lib/node_modules/jsonld-cli/node_modules/jsonld/js/jsonld.js:551:25
    at done (/usr/local/lib/node_modules/jsonld-cli/node_modules/jsonld/js/jsonld.js:286:18)
    at /usr/local/lib/node_modules/jsonld-cli/bin/jsonld:128:7
    at /usr/local/lib/node_modules/jsonld-cli/node_modules/jsonld-request/lib/request.js:328:9
    at _parse (/usr/local/lib/node_modules/jsonld-cli/node_modules/jsonld-request/lib/request.js:171:12)
    at /usr/local/lib/node_modules/jsonld-cli/node_modules/jsonld-request/lib/request.js:327:7
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:408:3)
Error: {
  "name": "jsonld.FrameError",
  "message": "Could not expand input before framing.",
  "details": {
    "cause": {
      "name": "jsonld.LoadDocumentError",
      "message": "Could not retrieve a JSON-LD document from the URL. URL dereferencing not implemented.",
      "details": {
        "code": "loading document failed",
        "cause": {
          "name": "jsonld.NullRemoteDocument",
          "message": "No remote document found at the given URL.",
          "details": {}
        },
        "remoteDoc": {
          "contextUrl": null,
          "documentUrl": "data.jsonld",
          "document": null
        }
      }
    }
  }
}
```

**Comment by mattcollier** [comment]
Are the `@context` documents in the source and the frame valid and available?  

You might try experimenting in the playground: https://json-ld.org/playground/

**Comment by jindrichmynarz** [comment]
Yes, both are valid. The JSONLD CLI tool works when the processed file is exposed via a local HTTP server (e.g., running `http-server` and `jsonld frame -f frame.jsonld http://localhost:8080/data.jsonld`).
